; Bảng nào Asterisk đọc từ database (Realtime)
[settings]
ps_endpoints  => odbc,asterisk
ps_auths      => odbc,asterisk
ps_aors       => odbc,asterisk
queues        => odbc,asterisk
queue_members => odbc,asterisk
